pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true // ensures container uses same workspace and Jenkins node
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./... 2>&1 | go-junit-report -set-exit-code > report.xml'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/report.xml'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir ('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}